version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tiradaus
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"   
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s
    networks: [mynetwork]

  api_rest:
    build:
      context: ./tiradaus
      dockerfile: Dockerfile
    container_name: tiradaus-api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tiradaus
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports: ["8080:8080"]
    networks: [mynetwork]

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge